// autogenerated: do NOT edit manually
using Platinum.Configuration;
using System;
using System.Configuration;

namespace Rhenium.Runtime.Asset
{
    public partial class ResolverConfiguration : ConfigurationSection
    {
        public static ResolverConfiguration Current
        {
            get { return AppConfiguration.SectionGet<ResolverConfiguration>( "rhenium/resolver" ); }
        }


        [ConfigurationProperty( "using", IsRequired = true )]
        public ResolverMethod ResolveUsing
        {
            get { return (ResolverMethod) this[ "using" ]; }
            set { this[ "using" ] = value; }
        }

        [ConfigurationProperty( "sources", IsDefaultCollection = false )]
        [ConfigurationCollection( typeof( ResolverSource ), AddItemName = "add" )]
        public ConfigurationElementCollection<ResolverSource> Sources
        {
            get { return (ConfigurationElementCollection<ResolverSource>) base[ "sources" ]; }
        }
    }


    public partial class ResolverSource : ConfigurationElement
    {
        [ConfigurationProperty( "name", IsKey = true, IsRequired = true )]
        public string Name
        {
            get { return (string) this[ "name" ]; }
            set { this[ "name" ] = value; }
        }

        [ConfigurationProperty( "directory", IsRequired = true )]
        public string Directory
        {
            get { return (string) this[ "directory" ]; }
            set { this[ "directory" ] = value; }
        }

        [ConfigurationProperty( "assembly", IsRequired = true )]
        public string Assembly
        {
            get { return (string) this[ "assembly" ]; }
            set { this[ "assembly" ] = value; }
        }
    }
}

/* eof */
